name: Build README.md

on:
  # on push to the repository
  push:
  # can be triggered manually
  workflow_dispatch:
  # on a schedule at minute 6 and 36 of each hour
  schedule:
    - cron: '6,36 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Npde
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v2
        name: Configure NPM caching
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install Node dependencies
        run: npm i
      - name: Update README.md
        env:
          CODEPUNKT_TOKEN: ${{ secrets.CODEPUNKT_TOKEN }}
        run: |-
          node src/build-readme.js
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git add -A
          git commit -m "chore: updated content" || exit 0
          git push
