name: Build README.md

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "6,26,46 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Npde
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/cache@v2
        name: Configure NPM caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Node dependencies
        run: npm i
      - name: Update README.md
        env:
          CODEPUNKT_TOKEN: ${{ secrets.CODEPUNKT_TOKEN }}
        run: |-
          node src/build-readme.js
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "chore: updated content" || exit 0
          git push
